config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  # Faz com que rota inicial da aplicação seja a page index (app/views/posts/index.html.erb), ou seja, a lista dos posts.
  resources :posts do 
  # Unico, pois utilizamos o scaffold para criar as rotas
  # depois será necessário criar uma para os comentários uma rota só e criaremos manualmente
    get :search, on: :collection #add rota para busca do tipo collection
  end

  resources :comments, only: %i[create] #rota de comentários, limitada a ação(action) de criação(create) - para não termos todas as rotas disponiveis, por questões ded segurança
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :body, presence: true
  
  belongs_to :post #pertence a um post
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch::Model
  extend FriendlyId

  validates :title, :author, :body, presence: true

  has_many :comments, dependent: :destroy #has_many :comments = um post tem vários commentários; dependent: :destroy = se apagar um post, apagar todos os comentários associados a este

  friendly_id :title, use: :slugged #slugged = É necessário que seja criado uma coluna slugged na tabela posts no BD para armazenar essa url
  # podemos criar parando o servidos, em seguida no terminal rodar o comando: rails g migration add_slug_column_to_posts slug:string

  pg_search_scope :search, 
    against: %i[title author body] #:search = Titulo do buscador; against: %i[title author body = contra quais campos do banco de dados vamos utilizar para fazer essa busca (nesse caso é titulo, autor e no corpo do texto); documentação: https://github.com/Casecommons/pg_search
    #associated_against: { comments: %i[body] } #associated_agaist: = busca em registros associados (nesse caso vai ser no corpo do texto dos comentários)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    #binding.pry #quando chegar nesse momento a aplicação vai parar e mostrar no terminal o que ta acontecendo
    comment = Comment.create!(comments_params) #salvar o comentário e aceitar os seguintes parametros/campos(), o create! serve para caso acontecer algo de errado, o usuário vai ver uma tela de erro

    redirect_to comment.post, notice: "Comentário enviado!"
    #redirect_to comment.post = redirencionar o usuário para o post (comment.post) depois da criação do comentário
    #notice: = mostrar a mensagem de "Comentário enviado!" - usar o help flash para exibir essa mensagem nas views
  end

  private #metodo privado 

  def comments_params
    params.require(:comment).permit(:post_id, :author, :body) #permit = permitir esses campos; o :post_id é um campo escondido no formulário que vai servir para linkar o comentário a seu post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc) # order(created_at: :desc) = ordenar os posts de acordo com a ordem decrescente de criação
  end

  def search
    @posts = Post.search(search_params[:q]) #esse método retorna uma coleção de posts, baseado no que o usuário buscou (search = esse nome da busca foi definido em model post.rb - ele virou um método da class post)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc) #ler todos comentários que conseguimos acessar em @post.comments, pois os comentários pertecem a um post(id)
    # order(created_at: :desc) = ordenar os comentários de acordo com a ordem decrescente de criação
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save #se salvar os posts
        format.html { redirect_to @post, notice: t(".notice") }
        format.json { render :show, status: :created, location: @post }
      else #se não salvar
        flash.now[:alert] = @post.errors.full_messages.to_sentence #flash.now[:alert] = Exibir uma mensagem de alerta (é necessário usar .now quando em seguida temos um render e não um redirect_to); 
        # @post = Instancia do banco de dados; 
        # .errors = Rach com varias informações sobre o erro; 
        # .full_messages = Retorna um array com todos os erros que ele encontrou; 
        # .to_sentence = Transforma tudo em uma frase.
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "O post foi atualizado com sucesso!" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "O post foi removido com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author, :body)
    end

    def search_params
      params.permit(:q)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog da Tabaresu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %> 
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
   
    <div class="p-4 mb-4 bg-dark text-center text-white"> <!-- 
    mb-4 p-4 : Definição de margem, borda e preenchimento (margin, border e padding) com CSS simplificado;
    bg-dark: Definição de cor do fundo do blog;
    text-center: Centralizar conteúdo;
    text-white: Definição da cor do texto, nesse caso é branco.
    Disponivel em: https://getbootstrap.com/docs/4.0/utilities/colors/
    -->
      <%= link_to root_path, class: 'text-white' do %> <!-- 
      link_to: Tag do Rails que cria um link para a rota inicial, quando clicar no titulo do blog. Boa prática de usabilidade;
      text-white: precisa adicionar novamente, pois a cor de texto definida anteriormente não se aplica aos links (encontramos essa exlicação na documentação do Bootstrap)
      -->
        <h1 class="display-4">Blog da Tabaresu</h1> <!-- Disponivel em: https://getbootstrap.com/docs/5.1/content/typography/#headings -->
      <% end %> <!--Fechamento do link-->
    
      <p class="lead">
        Olá, aqui você encontrará artigos sobre programação, tecnologia e carrreira. <!--Subtitulo-->
      </p>
    </div>

    <div class="container">
      <% flash.each do |type, message| %> <!-- Loop para exibir o array de mensagens(avisos) -->
      <div class="alert alert-<%= type == "alert" ? "dager" : "success" %> alert-dismissible fade show" role="alert"> <!--
      A cor vai ser alterada de acordo com o tipo de mensagem: 
      * darger para o tipo alert 
      * sucess para outros (notice)
      -->
        <%= message %> <!--Mensagem a ser exibida dinâmicamente-->

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> <!--Botão de fechar (close)-->
      </div>
      <% end %>

      <div class="row"> <!--Tabela para a busca-->
        <div class="col-4 offset-8"> <!--offset-8 = Ignorar as 8 primeiras colunas e pegar as 4 ultimas-->
          <div class="search">
            <%= form_with url: search_posts_path, method: :get, local: true, class: "form-inline" do |form| %>
              <div class="form-group mx-3 mb-3">
                <%= form.search_field :q, class: "form-control", required: true, placeholder: "Busca", value: params[:q] %> <!-- *required: true = Não permite buscar com o campo vazio
                * value: params[:q] = para salvar essa busca-->    
              </div>

              <%= form.submit "Buscar", class: "btn btn-dark mb-3",  
                data: { disable_with: "Buscando..." } %> <!--
                Flager(marcador) data { disable_with: "Buscando..."} = toda vez que submeter a atualização ou o novo post, vai desabilitar o botão e vai aparecer "buscando" -->
            <% end %>
          </div>
        </div>
      </div>

      <%= yield %> <!--Conteúdo da aplicação-->
    </div>

    <footer class="mt-5 p-4 bg-dark text-center text-white"> <!--Rodapé-->
    <!--
    mt-5 p-4 : Definição de margem de topo (aplica somente para cima), borda e preenchimento(quando não especificamos nem "b" nem "t" aplica para os dois) 
    (margin, border e padding) com CSS simplificado;
    bg-dark: Definição de cor do fundo do blog;
    text-center: Centralizar conteúdo;
    text-white: Definição da cor do texto, nesse caso é branco.
    Disponivel em: https://getbootstrap.com/docs/4.0/utilities/colors/
    -->
      Copyright © Nathallye Tabaresu <%= Date.current.year%>. <!--
      Date.current.year - 
      Utilizar a classe Date
      .current que pega a data atual
      .year para pegar o ano 
      Assim não teremos que digitar o ano, e mudar o código todos os anos, podemos usar o Rails para gerar o ano dinâmicamente
      -->
    </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div class="form-group mb-2"> <!--form-group = Padrão bootstrap. Disponível em: https://getbootstrap.com/docs/4.0/components/forms/-->
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %> <!--"form-control" = Padrão bootstrap de formatação de formulários. Disponível em: https://getbootstrap.com/docs/4.0/components/forms/-->
  </div>

  <div class="form-group mb-2"> 
    <%= form.label :author %>
    <%= form.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group mb-2"> 
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", rows: 5 %> <!--Flager rows(lista) = marcador-->
  </div>

  <%= form.submit class: "btn btn-dark", data: { disable_with: "Enviando..."} %>
  <!--Flager(marcador) data { disable_with: "Enviando..."} = toda vez que submeter a atualização ou o novo post, vai desabilitar o botão e vai aparecer "enviando" -->
<% end %>


<!--
OBS.: 
Toda a traduçaõ dos nomes dos itens dos formulários (tile, auhor, body...) foi feita no arquivo config/locales/pt-BR.yml
-->

app/views/posts/_post.html.erb
<!--Alguma coisa aqui -->
<!--Essa informação vai ficar se repetindo, por conta do nosso loop no arquio index.html.erb-->

<div class="card bg-light mb-3"> <!--
* Classe card na cor clara. Disponivel em: https://getbootstrap.com/docs/4.0/components/card/* mb-3 = margin border 3 para separar os cards-->
  <div class="card-body"> <!--Espaço entre os elementos-->
    <h4> <%= link_to post.title, post, class: "text-dark" %> </h4> <!--
    * post = lugar onde o usuário será redirecionado (próprio post)
    tradicionalmente essa rota é post_path(post) 
    mas como o nome da rota é examente o mesmo nome do objeto (parâmetro)
    podemos simplesmente passar apenas o objeto (post) que o rails entende esssa rota
    * tag <h4> pois é um titulo
    * class: "text-dark" = cor do texto preta
    -->
    <div class="text-muted mb-2"> <!-- text-muted = Texto fica cinzinha -->
      <em> Por <%= post.author %> (<%= I18n.l(post.created_at, format: :long) %>) </em> 
      <!-- 
      * post.author = mostrar dinamicamente o nome do autor do post
       * I18n.l = para mudar a formatação de data para a padrão do brasil
      o que vem depois do I18n.l é o parâmetro, ex.: (post.created_at) - que é a data e hora de criação do post
      * post.created_at = data de criação do post (mostra dinamicamente também)
      * format: = passando o parâmetro de formato
      * :long = em seguida passamos um simbolo long, que nada mais é que o formato longo que mostra o ano
      -->
      <!--Tag <em></em> deixa tudo em italico-->
    </div>

    <p> <%= post.body.truncate(200) %> </p> <!--post.body = Exibir conteúdo do post
    * .truncate(200) = limita o numero de caracteres mostrado em tela - (200) é número de carcteres-->

    <p class="text-muted" > <%= pluralize(post.comments.count, "Comentário") %> </p> <!-- 
    * text-muted = Texto fica cinzinha 
    * pluralize() = Esse método serve para pluralizar uma string quando for necessário, nesse caso quando o número de comentário for igual a 0, 2 ou mais...
    depois do método pluralize () passamos o número de registros a ser exibido nesse caso é post.comments.count
    e em seguida a string que vai ser pluralizada ou não (configuração feita no arquivo inflections.rb)
    * post.comments.count = Contar o número de comentários associados a esse post-->

    <%= link_to "Ler Artigo", post, class: "btn btn-dark" %> <!--
    * link_to "Ler Artigo" = Botão linkado para ler atigo
    * post = lugar onde o usuário será redirecionado (próprio post)
    * class: "btn btn-dark" = cor do botão preta
    -->

    <%= link_to "Editar", edit_post_path(post), class: "btn btn-secondary" %> <!--
    * link_to "Editar" = Botão linkado para editar atigo
    * edit_post = parâmetro de rota para edição usado depois de buscar na lista de rotas disponiveis para nossa aplicação no terminal (rails routes) 
    em seguida passa como parâmetro o post
    * class: "btn btn-secondary" = cor do botão cinza
    -->
    <%= link_to "Apagar", post, method: :delete, class: "btn btn-danger", 
      data: {confirm: "Você tem certeza que deseja apagar esse post?"} %> <!--
    * link_to "Apagar" = Botão linkado para apagar atigo
    * post = Pois a rota dele é a mesma do botão "ler atigo", porém o método é "deletar"
    * method: :delete = Dessa forma o rails entende que essa rota é para apagar
    * class: "btn btn-danger" = cor do botão vermelha
    * data: {confirm: "string"} = Método do Rails para confirmar se deseja apagar mesmo
    -->
  </div>  
</div>

app/views/posts/edit.html.erb
<h1>Editar Post</h1>

<%= render 'form', post: @post %> <!-- Temos aqui o path form, que já renderiza a página de formulário aqui e no "new post(novo post)" -->

app/views/posts/index.html.erb
<% @posts.each do |post| %> <!--Loop dos posts-->
  <!--Conteúdo-->
  <!--Vamos utilizar um recurso do Rails que são as paths. 
  Ou seja, o conteúdo que iria aqui vamos colocar em outro arquivo, pois assim podemos usar esse mesmo conteúdo para exibir em outras partes da aplicação-->
  
  <!--MUDAR ISSO: --> 
  <!--
  render 'post', post: post 
  * render = Renderizar a paths (não esquecer do sinal de igual)
  * 'post' = nome da path
  * post: post = passa como parâmetro de post o post
  -->

  <!--PARA ISSO: -->
  <%= render(post) %> 
  <!-- render(post) = podemos apenas passar uma variavél como parâmetro (virando um metódo), para não ficar muito "feio". -->
<% end %>

<!-- <% %> Tag do Rails para add um código dinâmico. -->

<!-- 
EXPLICAÇÃO DO QUE ACONTECE AQUI:
* @posts.eatch do |post| = Quando a gente passa um objeto que tá vindo do banco, no caso, os @posts é uma coleção(um  array) de elementos do banco.
* render(post) = Quando passamos para o render (esse método) ele já vai automáticamente procurar no projeto um arquivo no diretório: app/views/posts/_posts.html.erb (automáticamente converte para essa url dinâmicamente - para isso será necessário criar esse arquivo nesse diretório. ). 
-->


<hr> <!--Criar linha horizontal-->

<div class="text-right"> <!--text-right = texto alinhado para direita-->
  <%= link_to "Criar novo post", new_post_path, class: "btn btn-success" %>
  <!--
  * link_to "Criar novo post" = criar botão com link com o nome "Criar novo post"
  * new_post = parâmetro de rota usado depois de buscar na lista de rotas disponiveis para nossa aplicação no terminal (rails routes)
  * class: "btn btn-success" = formatar botão na cor verde
  disponivel em: https://getbootstrap.com/docs/4.0/components/buttons/#button-tags
  -->
</div>

app/views/posts/new.html.erb
<h1>Novo Post</h1>

<%= render 'form', post: @post %> <!-- Temos aqui o path form, que já renderiza a página de formulário aqui e no "editing post(editar post)" -->

app/views/posts/search.html.erb
<h2 class="text-muted">  <!-- class text-muted = Texto fica cinzinha-->
  <% if @posts.any? %>  <!--Se encontrar algum post/resultados-->
    <%= pluralize(@posts.count, "resultado encontrado") %>
  <% else %>
    Nenhum resultado encontrado.
  <% end %>
</h2>

<!--Exibir os resultados dos posts: Vai fazer um loop dos posts e renderizar cada um deles-->
<% @posts.each do |post| %> <!--Loop dos posts-->
  <!--Conteúdo-->
  <!--Vamos utilizar um recurso do Rails que são as paths. 
  Ou seja, o conteúdo que iria aqui vamos colocar em outro arquivo, pois assim podemos usar esse mesmo conteúdo para exibir em outras partes da aplicação-->
  
  <!--MUDAR ISSO: --> 
  <!--
  render 'post', post: post 
  * render = Renderizar a paths (não esquecer do sinal de igual)
  * 'post' = nome da path
  * post: post = passa como parâmetro de post o post
  -->

  <!--PARA ISSO: -->
  <%= render(post) %> 
  <!-- render(post) = podemos apenas passar uma variavél como parâmetro (virando um metódo), para não ficar muito "feio". -->
<% end %>

<!-- <% %> Tag do Rails para add um código dinâmico. -->

<!-- 
EXPLICAÇÃO DO QUE ACONTECE AQUI:
* @posts.eatch do |post| = Quando a gente passa um objeto que tá vindo do banco, no caso, os @posts é uma coleção(um  array) de elementos do banco.
* render(post) = Quando passamos para o render (esse método) ele já vai automáticamente procurar no projeto um arquivo no diretório: app/views/posts/_posts.html.erb (automáticamente converte para essa url dinâmicamente - para isso será necessário criar esse arquivo nesse diretório. ). 
-->

<div>

</div>

app/views/posts/show.html.erb
  <div class="shadow p-5 bg-light rounded"> 
    <div class="text-center mb-5"> <!--text-center  = centralizar o texto da div-->
      <h1> <%= @post.title %> </h1>
      <p class="text-muted"> <!-- class text-muted = Texto fica cinzinha-->
        <strong> Por <%= @post.author %> </strong> <br> <!--
        * Tag strong para ficar em negrito; 
        * post.author = mostrar dinamicamente o nome do autor do post
        * Tag br para fazer uma quebra de linha
        -->
        <%= I18n.l(@post.created_at, format: :long) %>
        <!-- 
        * I18n.l = para mudar a formatação de data para a padrão do brasil
        o que vem depois do I18n.l é o parâmetro, ex.: @post.created_at - que é a data e hora de criação do post
        * @post.created_at = data de criação do post (mostra dinamicamente também)
        * format: = passando o parâmetro de formato
        * :long = em seguida passamos um simbolo long, que nada mais é que o formato longo que mostra o ano
        -->
      </p>
    </div>

    <div class="px-5"> <!--px aplica o espaço só na horizontal; py aplica o espaço só na vertical-->
       <%= @post.body.gsub("\n", "<br>").html_safe %> <!--
       * .gsub() = método para exibir a quebra de linha, pois está salvo no banco de dados como "\n" e precisa ser salvo com <br> 
       * ("\n", "<br>") = dentro vamos passar os parâmetros, o primeiro o que queremos substituir e em seguida para que elemento vamos substituir 
       * .html_safe = informar que o html é seguro para que ele não somente renderize a tag <br> e sim faça a quebra de linha 
       -->
    </div>
  </div>

  <div class="m-5">
    <div class="text-center">
      <h4> 
        <%= pluralize(@post.comments.count, "Comentário") %> <!--
      * tag <h4> pois é um titulo
      * pluralize() = Esse método serve para pluralizar uma string quando for necessário, nesse caso quando o número de comentário for igual a 0, 2 ou mais...
      depois do método pluralize () passamos o número de registros a ser exibido nesse caso é @post.comments.count
      e em seguida a string que vai ser pluralizada ou não (configuração feita no arquivo inflections.rb)
      * @post.comments.count = Contar o número de comentários associados a esse post
      * Aqui fica @post, pois é uma variável de instância
      -->
        <% if (@post.comments.count == 0) %> <!--Se o total de commentários for igual a zero-->
          <span class="badge badge-success">Seja o primeiro a comentar!</span> <!--badge bg-success = Criação de Tag-->
        <% end %>
      </h4> 
    </div>

    <div class="shadow-sm m-3 p-3 bg-light rounded"> <!--shadow-sm = Sombra com m-3; bg-light = fundo cinza; rounded = arredondado-->
      <%= form_with model: @comment, local: true do |form| %> <!-- 
       * form_with = Help do Rails para criação de formulário 
       model: @comment = passamos o objeto vazio do controler para armazenar

       * local: true do |form| = Não utilizar ajax de acordo com o padrão do Rails
       -->
        <%= form.hidden_field :post_id, value: @post.id %> <!--Campo escondido do id do post, para associar lá no controller dos comentários a que post determinado comentário pertence -->

        <div class="form-group mb-2"> 
          <%= form.label :author %>
          <%= form.text_field :author, class: "form-control", required: true %>
        </div>

        <div class="form-group mb-2"> 
          <%= form.label :body %>
          <%= form.text_area :body, class: "form-control", rows: 2, required: true %> <!--Flager rows(lista) = marcador-->
        </div>

        <%= form.submit 'Enviar', class: "btn btn-dark", 
          data: { disable_with: "Enviando..."} %> <!--
        Flager(marcador) data { disable_with: "Enviando..."} = toda vez que submeter a atualização ou o novo post, vai desabilitar o botão e vai aparecer "enviando" -->
      <% end %>
    </div>

    <% @comments.each do |comment| %> <!--Exibir um em loop o array de comentários definidos lá no arquivo de post_controller:
    def show
      @comments = @post.comments #ler todos comentários que conseguimos acessar em @post.comments
    end
    essa variável @post foi definida pelo scafald-->
      <div class="shadow-sm m-3 p-3 bg-light rounded"> <!--shadow-sm = Sombra com m-3; bg-light = fundo cinza; rounded = arredondado-->
        <div class="row"> <!--row = fileira-->
          <div class="col"> <!--col = coluna-->
            <strong> <%= comment.author %> </strong> <!--Nome do autor do comentário-->
          </div>

          <div class="col text-right"> <!--col = coluna; text-right = texto alinhado para direita-->
            <em data-toggle="tooltip" data-placement="top" title="<%= I18n.l(comment.created_at, format: :long) %>"> <!--
            * tooltips para exibir a data e hora exata de criação quando o usuário passar o cursor sobre o tempo relativo. Disponivel em: https://getbootstrap.com/docs/4.0/components/tooltips/
            * Não esquecer de ativar via javascript no arquivo application.js
            -->
              <%= time_ago_in_words comment.created_at %> atrás 
            </em> <!--
            * comment.created_at = Data de criação do comentário
            * time_ago_in_words = Formata em tempo relativo (ex.:17min atrás)
            -->
          </div>
        
        </div>

        <hr> <!--Quebra de linha horizontal-->
        <%= sanitize(comment.body.gsub("\n", "<br>")).html_safe %> <!--
        * sanitize = Remove qualquer script malicioso
        * comment.body = Exibir o texto dos comentários
        * .gsub() = método para exibir a quebra de linha, pois está salvo no banco de dados como "\n" e precisa ser salvo com <br> 
        * ("\n", "<br>") = dentro vamos passar os parâmetros, o primeiro o que queremos substituir e em seguida para que elemento vamos substituir 
        * .html_safe = informar que o html é seguro para que ele não somente renderize a tag <br> e sim faça a quebra de linha 
       -->
      </div>
    <% end %>
  </div>

  
  
 